### ISSUE TITLE
Uniqueness validations need work

### ISSUE THREAD

**Issue by astjohn** [reidmorrison/symmetric-encryption#53]
As I was further securing personal information throughout our app, I realized that the uniqueness validations are broken. I set up some preliminary failing tests here: 983e3649731ee901b100d4907cb49d599777fea0

This is a priority for me so I'll see what I can do, but any insight you might have is greatly appreciated.

**Comment by reidmorrison** [comment]
Currently to validate uniqueness, we have to do it against the encrypted column:

```ruby
class UniqueUser < ActiveRecord::Base
  attr_encrypted :email
  attr_encrypted :username

  validates_uniqueness_of :encrypted_email, allow_blank: true, if: :encrypted_email_changed?
  validates_uniqueness_of :encrypted_username, allow_blank: true, if: :encrypted_username_changed?
  validates :username, length: {in: 3..20},
    format:                    {with: /\A[\w\d\-[[:alnum:]]]+\z/},
    allow_blank:               true
end
```

This approach "works", but it does not work seamlessly with the user interface. For example if someone enters an email address that already exists, then the Rails magic to highlight the email address along with the duplicate field name does not just work and the validation message would mention the encrypted column name.

Does this meet your needs or are you also looking for the transparent hookup with the UI?
This would however be a significant undertaking since we would have to patch rails to use the encrypted column under the covers when the unencrypted column name is used in a validation. Open to ideas and suggestions to get this working though.

Unfortunately, it is not feasible to do case-insensitive uniqueness validations since the existing values are already encrypted. To do a case-insensitive validation it would have to decrypt every value in the database and then manually perform a case-insensitive comparison with the new value.
We prefer to use data cleansing up front to for example convert email addresses to uppercase or lowercase before saving. See: https://github.com/reidmorrison/data_cleansing

**Comment by astjohn** [comment]
Yeah. I started looking at what would be required for monkey patching support and it will be a nightmare to maintain.  The workaround you suggested is great. To do case-insensitive, we will simply store a sanitized version that we can compare against.

Thanks for your input!
